### ISSUE TITLE
Please add a new method name, like useStateRef to be able to use both useState and useStateRef at the same time

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [Aminadav/react-useStateRef#5]
like the title says, I would like to keep the things seperated?

**Comment by dominic-heil** [comment]
There is no need for this. As the custom hook is exported as default you can name it whatever you want. You can use the default React useState and useStateRef simultaniousely using the following imports:

```
import React, {useState} from "react";
import useStateRef from 'react-usestateref'
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah I see, great, thanks! ❤️
