### ISSUE TITLE
🧙‍♂️ Typescript support

### ISSUE THREAD

**Issue by Giuseppetm** [Aminadav/react-useStateRef#7]
Hello, I tried to use this package along with Typescript, but I had some problems.
The main problem is that there isn't a @types/react-usestateref.

![image](https://user-images.githubusercontent.com/52317197/131228072-4be10788-2efa-476c-b626-81a721c6bf6f.png)

So I tried to use this method:

`Add a new declaration (.d.ts) file containing "declare module 'react-usestateref';"`

I created the global.d.ts file containing this code:

```typescript
declare module 'react-usestateref';
```

but after that I got type errors when using the useState unfortunately.

![image](https://user-images.githubusercontent.com/52317197/131227973-6dce42b6-16ad-483c-beaf-e852206f2efa.png)

It would be really great to have typescript support as well; let me know! 😊

**Comment by lmichelin** [comment]
Hello, I already opened a PR (#6) to migrate to TypeScript, I hope it will be merged soon 😃

**Comment by Giuseppetm** [comment]
> Hello, I already opened a PR (#6) to migrate to TypeScript, I hope it will be merged soon 😃

Yeah, I saw it after opening the issue. Thank you very much :)
